export const urls = [
  {
    url: "https://thecatconnection.org/pawmestry-the-art-of-reading-toe-beans/",
    text: "Paw Reading",
  },
  {
    url: "https://www.dailypaws.com/living-with-pets/pet-compatibility/cat-horoscopes/what-your-cats-zodiac-sign-tells-you",
    text: "Horoscopes",
  },
  {
    url: "https://www.cats.org.uk/help-and-advice/getting-a-cat/pet-insurance",
    text: "Insurance",
  },
];

export const textContent = {
  card: {
    title: "Interesting Cat Names",
    content: "Here are some interesting cat names to consider for your new furry friend:",
    button: "Show cat names!",
  },

  dialog: {
    dialogTitle: "Interesting Cat Names",
    deletedLastMessage: "You've deleted the last item!",
    deletedLastImg: "https://placecats.com/millie/300/150",
    smallerCatNames: [
      "Whiskers",
      "Mittens",
      "Luna",
      "Simba",
      "Ginger",
      "Oliver",
      "Shadow",
      "Smokey",
      "Salem",
      "Cleo",
      "Sassy",
      "Oreo",
      "Tigger",
      "Paws",
      "Boots",
      "Felix",
      "Pepper",
      "Misty",
      "Ember",
      "Mystic",
      "Orion",
      "Lucky",
      "Jazz",
      "Gizmo",
      "Fuzzy",
      "Skye",
      "Willow",
      "Maple",
      "Echo",
      "Twilight",
      "Dusk",
      "Dawn",
      "Emberly",
      "Flicker",
      "Mirage",
      "Zephyr",
      "Poe",
      "Dante",
      "Byron",
      "Wilde",
      "Kipling",
      "Rumi",
      "Emerson",
    ],
    catNames: [
      "Whiskers",
      "Mittens",
      "Luna",
      "Simba",
      "Ginger",
      "Oliver",
      "Shadow",
      "Smokey",
      "Salem",
      "Cleo",
      "Sassy",
      "Oreo",
      "Tigger",
      "Paws",
      "Boots",
      "Felix",
      "Pepper",
      "Misty",
      "Tiger",
      "Callie",
      "Midnight",
      "Pippin",
      "Pebbles",
      "Biscuit",
      "Muffin",
      "Pounce",
      "Snickers",
      "Bandit",
      "Zorro",
      "Sable",
      "Nova",
      "Cosmo",
      "Poppy",
      "Dusty",
      "Cookie",
      "Clover",
      "Spark",
      "Velvet",
      "Ember",
      "Mystic",
      "Orion",
      "Lucky",
      "Jazz",
      "Gizmo",
      "Fuzzy",
      "Skye",
      "Willow",
      "Maple",
      "Echo",
      "Storm",
      "Comet",
      "Astro",
      "Neptune",
      "Pluto",
      "Stardust",
      "Galaxy",
      "Celeste",
      "Breeze",
      "Whimsy",
      "Nimbus",
      "Frost",
      "Sunkist",
      "Autumn",
      "Solstice",
      "Twilight",
      "Dusk",
      "Dawn",
      "Emberly",
      "Flicker",
      "Mirage",
      "Zephyr",
      "Tempest",
      "Rain",
      "Mist",
      "Cosmos",
      "CometTail",
      "Haze",
      "Aurora",
      "Euphoria",
      "Seraph",
      "Quasar",
      "Eclipse",
      "Orbit",
      "Gravity",
      "Stellar",
      "NovaStar",
      "Meteor",
      "Asteroid",
      "Celestial",
      "LunaRose",
      "Sparkle",
      "Velvetine",
      "Radiance",
      "Luster",
      "Glimmer",
      "Halo",
      "Prism",
      "Solara",
      "Twilight Gleam",
      "Aurora Sky",
      "Emberlyn",
      "Stardustia",
      "Moonbeam",
      "Silhouette",
      "Dapple",
      "Purrfect",
      "Sir Meows-a-Lot",
      "Count Whiskerton",
      "Lady Pounce",
      "Duchess",
      "Baroness",
      "Admiral",
      "Captain Whisker",
      "Admiral Fluff",
      "Professor Paws",
      "Squire",
      "Noble",
      "Regal",
      "Majestic",
      "Emperor",
      "Queenie",
      "King",
      "Prince",
      "Duchess Dot",
      "Fancy",
      "Velvet Paws",
      "Sir Purr",
      "Madam Meow",
      "Lord Whiskers",
      "Duchess Fuzz",
      "Countess",
      "Marquis",
      "Earl",
      "Viscount",
      "Purrlock Holmes",
      "Watson",
      "Sherlock",
      "Gatsby",
      "Hemingway",
      "Fitzgerald",
      "Poe",
      "Dante",
      "Byron",
      "Wilde",
      "Kipling",
      "Rumi",
      "Emerson",
      "Whitman",
      "Shakespeare",
      "Austen",
      "Brontë",
      "Poe’s Paws",
      "Faulkner",
      "Kip",
      "Hemingway (II)",
      "Atticus",
      "Scout",
      "Darcy",
      "Rochester",
      "Gatsby Whiskers",
      "Hemingway’s Cat",
      "Austen’s Muse",
      "Purrcival",
      "T.S. Eliot",
      "Whiskerstein",
      "Catniss",
      "Meowly",
      "Furrdinand",
      "Purrscilla",
      "Tabitha",
      "LunaBelle",
      "Purrcy",
      "Felixious",
      "Mews",
      "Purrfecto",
      "Whispurr",
      "Furrlina",
      "Whiskaria",
      "Purrkins",
      "Furrball",
      "Pouncey",
      "Nimble",
      "Zippy",
      "Slinky",
      "Breezy",
      "Frolic",
      "Skitter",
      "Whirl",
      "Zest",
      "Jitter",
      "Frisky",
      "Prancer",
      "Sprightly",
      "Dazzle",
      "Glint",
      "Flash",
      "Zing",
      "Sprint",
      "Zippy Zoom",
      "Fizz",
      "Whiskerdoo",
      "Purrito",
      "Furrtastic",
      "Catnado",
      "Purrminator",
      "Furball Supreme",
      "Sir Fuzzington",
      "Pounce de Leon",
      "Catnificent",
      "Meowstro",
      "Meowzart",
      "Purrdini",
      "Furraldo",
      "Catastrophe",
      "Meowculus",
      "Pawsitive",
      "Pawsitivity",
      "Whiskerwhirl",
      "Meowlody",
      "Purrvana",
      "Catnip",
      "Furrnando",
      "Purrcasso",
      "Catastrophina",
      "Fuzz Aldrin",
      "Meowlin",
      "Purrcival II",
      "Catmandu",
      "Purrlock",
      "Furrend",
      "Purrl",
      "Meowgic",
      "Purrfection",
      "Cataclysm",
      "Furrniture",
      "Catnippy",
      "Whiskerlicious",
      "Purrsimon",
      "Catamaran",
      "Meowtain",
      "Purrfectionist",
      "Catacomb",
      "Furrlight",
      "Meowgician",
      "Purradox",
      "Catniss Everclean",
      "Fuzzbuster",
      "WhiskerWonder",
      "Meowntain",
      "Purrade",
      "Furrytail",
      "Catapult",
      "Purrlicious",
      "Whispurr",
      "Catina",
      "Furrtique",
      "Catitude",
      "Purrfectionado",
      "Whiskerina",
      "Catkins",
      "Furrytastic",
      "Meowster",
      "Purrlina",
      "Catanova",
      "Furrmont",
      "Whiskerella",
      "Meowser",
      "Purrlina Grace",
      "Catkin",
      "Furrytale",
      "Whiskerwisp",
      "Meowgical",
      "Purrfectionista",
      "Catnap",
      "Furrific",
      "Whiskerful",
      "Meowzen",
      "Purrtastic",
      "Catty",
      "Furrlic",
      "Whiskerwind",
      "Meowmuse",
      "Purrlight",
      "Catacorn",
      "Furrsational",
      "Whiskerwhip",
      "Meowserine",
      "Purrblossom",
      "Catnado II",
      "Furrificus",
      "Whiskerwise",
      "Meowley",
      "Purrbloom",
      "Catopia",
      "Furrabelle",
      "Whiskerwinks",
      "Meowtini",
      "Purrspark",
      "Catamuse",
      "Furrscover",
      "Whiskerwind (II)",
      "Meowmosa",
      "Purrsade",
      "Catitude Deluxe",
      "Furrharmony",
      "Whiskerwhisper",
      "Meowstique",
      "Purrley",
      "Catmint",
      "Furranova",
      "Whiskerella II",
      "Meowberry",
      "Purrsuit",
      "Catnipton",
      "Furridian",
      "Whiskerwick",
      "Meowlynn",
      "Purrcious",
      "Catmopolitan",
      "Furrlicious",
      "Whiskerwaltz",
      "Meowzella",
      "Purrglow",
      "Catastro",
      "Furrzest",
      "Whiskerfizz",
      "Meowshine",
      "Purrvana II",
      "Catadelic",
      "Furrique",
      "Whiskerwisp II",
      "Meowtastic",
      "Purrfecta",
      "Catacoustic",
      "Furrie",
      "WhiskerDazzle",
      "Meowmixer",
      "PurrMoon",
      "Catastrofic",
      "Furrgleam",
      "WhiskerBeam",
      "Meowlody",
      "PurrCharm",
      "CatCosmo",
      "FurrSonic",
      "WhiskerSpark",
      "MeowFlare",
      "PurrMystic",
      "CatNova",
      "FurrCeleste",
      "WhiskerMuse",
      "MeowAura",
      "PurrLuxe",
      "CatVibe",
      "FurrLoom",
      "WhiskerRift",
      "MeowFusion",
      "PurrEcho",
      "CatNovae",
      "FurrSation",
      "WhiskerQuake",
      "MeowPlex",
      "PurrZing",
      "CatTastic",
      "FurrVivid",
      "WhiskerOrbit",
      "MeowPulse",
      "PurrStream",
      "CatRift",
      "FurrTwist",
      "WhiskerBlend",
      "MeowZenith",
      "PurrGlide",
      "CatGlitter",
      "FurrSprout",
      "WhiskerWaltz (II)",
      "MeowLyric",
      "PurrEclipse",
      "CatWhirl",
      "FurrGlimmer",
      "WhiskerNova",
      "MeowSonic",
      "PurrStellar",
      "CatMingle",
      "FurrMystique",
      "WhiskerPulse",
      "MeowFable",
      "PurrGalaxy",
      "CatSonic",
      "FurrZen",
      "WhiskerRealm",
      "MeowNectar",
      "PurrDimension",
      "CatFusion",
      "FurrIllume (I)",
      "WhiskerLuxe",
      "MeowVortex",
      "PurrOdyssey",
      "CatVoyage",
      "FurrOdyssey",
      "WhiskerLegend",
      "MeowEpic",
      "PurrSaga",
      "CatChronicle",
      "FurrTale",
      "WhiskerMyth",
      "MeowLore",
      "PurrFable",
      "CatRhapsody",
      "FurrBallad",
      "WhiskerBallad",
      "MeowEpicure",
      "PurrVerse",
      "CatOde",
      "FurrSonnet",
      "WhiskerSonnet",
      "MeowEulogy",
      "PurrElegy",
      "CatCantata",
      "FurrCantata",
      "WhiskerRhythm",
      "MeowTempo",
      "PurrBeat",
      "CatHarmony",
      "FurrChord",
      "WhiskerMelody",
      "MeowTune",
      "PurrSymphony",
      "CatConcerto",
      "FurrConcerto",
      "WhiskerOpera",
      "MeowAria",
      "PurrCrescendo",
      "CatOverture",
      "FurrRhapsody",
      "WhiskerChime",
      "MeowChorus",
      "PurrSerenade",
      "CatLullaby",
      "FurrLullaby",
      "WhiskerDitty",
      "MeowBallad",
      "PurrCanticle",
      "CatHymn",
      "FurrHymn",
      "WhiskerChant",
      "MeowMantra",
      "PurrMantra",
      "CatMystery",
      "FurrMystery",
      "WhiskerEnigma",
      "MeowCipher",
      "PurrPuzzle",
      "CatConundrum",
      "FurrRiddle",
      "WhiskerMystery",
      "MeowWhisper",
      "PurrSecret",
      "CatEclipse",
      "FurrEclipse",
      "WhiskerCosmos",
      "MeowFrost",
      "PurrGlitter",
      "CatFrost",
      "FurrFrost",
      "WhiskerBliss",
      "MeowBliss",
      "PurrBliss",
      "CatCharm",
      "FurrCharm",
      "WhiskerGleam",
      "MeowGleam",
      "PurrGleam",
      "CatGlimmer",
      "FurrGlimmer",
      "WhiskerSparkle",
      "MeowSparkle",
      "PurrSparkle",
      "CatTwinkle",
      "FurrTwinkle",
      "WhiskerTwinkle",
      "MeowTwinkle",
      "PurrTwinkle",
      "CatShimmer",
      "FurrShimmer",
      "WhiskerShimmer",
      "MeowShimmer",
      "PurrShimmer",
      "CatRadiance",
      "FurrRadiance",
      "WhiskerRadiance",
      "MeowRadiance",
      "PurrRadiance",
      "CatIllume",
      "FurrIllume (II)",
      "WhiskerIllume",
      "MeowIllume",
      "PurrIllume",
      "CatLustre",
      "FurrLustre",
    ],
  },
};
